### ISSUE TITLE
Prompt declarations in README.md to not match the code

### ISSUE THREAD

**Issue by markhallen** [OlympiaAI/raix#8]
In the readme the suggested usage of the prompt declaration is `prompt call: ModelName`, however in the `PromptDeclaration` model there is no `call` argument and there is a required `text` argument.

## Readme

https://github.com/OlympiaAI/raix/blob/3c229d85395892adfde37cd864d5f9a045123fcc/README.md?plain=1#L197-L207

## `PromptDeclarations`

https://github.com/OlympiaAI/raix/blob/3c229d85395892adfde37cd864d5f9a045123fcc/lib/raix/prompt_declarations.rb#L15-L22

## Error

If we try to instantiate the class containing the `prompt` declaration we get the `missing keyword: :text (ArgumentError)`:

```ruby
test-app(dev)> MyModelName.new("What is the meaning of life?")
app/models/my_model_name.rb:7:in `<class:MyModelName>': missing keyword: :text (ArgumentError)
        from app/models/my_model_name.rb:1:in `<main>'
```

Example model

```ruby
# app/models/my_model_name.rb

class MyModelName
  include Raix::ChatCompletion
  include Raix::PromptDeclarations

  attr_accessor :conversation

  prompt call: MyOtherModel

  def initialize(conversation)
    self.conversation = conversation
  end
end
```

## Summary

I'm not sure how to use my other ChatCompletion model in this DSL. If we can figure it out I will raise a PR to update the docs.

**Comment by markhallen** [comment]
`prompt text: -> { MyOtherModel }` seems to work.

**Comment by martinemde** [comment]
There's another one when `response_format` is passed to chat_completion, it needs to be passed like `params: {response_format: format}` but the README.md passes it directly.

Speaking of, why are these pulled out as `params` instead of kwargs?

**Comment by obie** [comment]
Agreed that params should be kwargs, will schedule for 1.0 somewhat soon.

**Comment by obie** [comment]
Great news\! This issue has been fixed in version 1.0.1 which is now available on RubyGems.

The fixes include:
- ✅ PromptDeclarations is now properly namespaced under `Raix`
- ✅ Removed Rails dependencies (Rails.logger, Honeybadger) 
- ✅ Added comprehensive tests to verify both `prompt call:` and `prompt text:` syntaxes work correctly

You can update to the latest version:
```ruby
gem 'raix', '~> 1.0.1'
```

Then run `bundle update raix`.

Thanks again for reporting this issue - your feedback helped make Raix better\! 🙏
